### ISSUE TITLE
Spelling error in "Insert"

### ISSUE THREAD

**Issue by lilopkins** [Some-Birb7190/email_signatures#1]
https://github.com/Some-Birb7190/email_signatures/blob/8582c4ad54ae65d1fc01be252f41fc900fbb18e1/signatures.txt#L117

**Comment by Some-Birb7190** [comment]
Resolved with [4887996](https://github.com/Some-Birb7190/email_signatures/commit/48879968ef16f2b87c7dee05b8a896bcb4d07c0f)
